export enum MutationTypes {
  SET_MONEY_TO_CONVERT = "SET_MONEY_TO_CONVERT",
  SET_CONVERTATION_MAP = "SET_CONVERTATION_MAP",
  SET_CONVERT_CCY = "SET_CONVERT_CCY",
  SET_CONVERTATION_RESULT = "SET_CONVERTATION_RESULT"
}

export enum ActionTypes {
  GET_CONVERTATION_MAP = "GET_CONVERTATION_MAP",
  GET_CONVERT_CCV = "GET_CONVERT_CCV",
  GET_CONVERTATION_RESULT = "GET_CONVERTATION_RESULT"
}
